// app/components/pages/home/Hobby.vue
<template>
  <div id="hobbies" class="container mx-auto px-6">
    <div class="mb-16">
      <h1 class="mb-4 text-center text-5xl font-semibold text-white">
        ⌈ Hobbies ⌋
      </h1>
    </div>
    <div class="flex justify-center">
      <div class="flex flex-wrap justify-center gap-8">
        <div
          v-for="(hobby, idx) in hobbyData"
          :key="idx"
          class="flex h-auto min-h-[180px] w-full flex-col items-center rounded-lg border border-transparent bg-[#1a222c] p-4 shadow transition-all duration-300 hover:border-gray-600 sm:w-[350px] sm:flex-row sm:items-center sm:p-6 md:w-[400px] lg:w-[550px]"
        >
          <div
            class="mb-2 flex justify-center text-4xl sm:mr-6 sm:mb-0 sm:text-5xl md:text-6xl"
          >
            {{ hobby.icon }}
          </div>
          <div class="text-center sm:text-left">
            <h2 class="mb-2 text-xl font-bold text-white sm:text-2xl">
              {{ hobby.title }}
            </h2>
            <p class="text-sm text-gray-300 sm:text-base">
              {{ hobby.desc }}
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import hobbyData from "~/data/hobbyData.json";
</script>

// src/sections/hobby.tsx
import hobbyData from "../data/hobbyData.json";

export default function Hobby() {
  return (
    <div className="container mx-auto px-6" id="hobbies">
      <div className="mb-16">
        <h1 className="text-5xl text-white font-semibold text-center mb-4">
          ⌈ Hobbies ⌋
        </h1>
      </div>
      <div className="flex justify-center">
        <div className="flex flex-wrap gap-8 justify-center">
          {hobbyData.map((hobby, idx) => (
            <div
              key={idx}
              className="bg-[#1a222c] w-full sm:w-[350px] md:w-[400px] lg:w-[500px] h-auto min-h-[180px]
                                       flex flex-col sm:flex-row items-center sm:items-center
                                       p-4 sm:p-6 rounded-lg shadow
                                       border border-transparent transition-all duration-300
                                       hover:border-gray-600"
            >
              <div className="text-4xl sm:text-5xl md:text-6xl mb-2 sm:mb-0 sm:mr-6 flex justify-center">
                {hobby.icon}
              </div>
              <div className="text-center sm:text-left">
                <h2 className="text-xl sm:text-2xl font-bold text-white mb-2">
                  {hobby.title}
                </h2>
                <p className="text-gray-300 text-sm sm:text-base">
                  {hobby.desc}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
